---
title: "treemap_hc"
output: html_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(echo = F, 
message = F,
warning = F, 
fig.asp = 0.8, 
fig.width = 7, 
out.width = "100%",
dpi = 300,
collapse = TRUE,
comment = "#>"
) 
```

```{r setup}
library(dplyr)
library(tidyr)
library(highcharter)
library(quanteda)
library(ggthemes)
library(ggfittext)
library(plotly)
library(RColorBrewer)
```

```{r}

n <- 1000
    BD <- tibble(
    id = 1:n,
    tipoEvento = sample(c("Político", "Electoral", "Acto de\nCampaña"), n, replace = T),
    candidato = sample(c("candidato 1", "candidato 2", "candidato 3", "candidato 4"), n, replace = T),
    percepcion = sample(c("Buena", "Mala", "Regular"), n, replace = T),
    mencionGenerada = sample(c("Boletines\n de prensa", "declaraciones", "filtraciones"), n, replace = T),
    mencionNoGenerada = sample(c("personaje", "columnista", "adversario", "partidario"), n, replace = T),
    calif_generada = sample(c("Mala", "Buena", "Regular"), n, replace = T),
    calif_no_generada = sample(c("Buena", "Mala", "Regular"), n, replace = T)
    )
    
```

```{r}
base1 <- BD %>% 
         select(mencionGenerada) %>% 
         unique() %>% 
         mutate(color=if_else(mencionGenerada=="Boletines\n de prensa", "#174a80", 
                      if_else(mencionGenerada=="declaraciones","#00A896","#ffc200")),
                id = str_to_id(mencionGenerada)
                )%>%
         rename("name"="mencionGenerada")


base2 <- BD %>% 
         count(percepcion, mencionGenerada) %>% 
         mutate(color=if_else(percepcion=="Buena",
                              "#0f4c42",                     
                      if_else(percepcion=="Mala",
                            "#cb2833","#808080")),
                parent=str_to_id(mencionGenerada),
                id = as.character(row_number())) %>% 
        rename("name"= "percepcion", "value"="n")
dde <- list(base1, base2) %>%
  purrr::map(mutate_if, is.factor, as.character) %>% 
  bind_rows() %>% 
  list_parse() %>% 
  purrr::map(function(x) x[!is.na(x)])
highchart() %>% 
  hc_chart(type = "treemap") %>% 
  hc_title(
    text = "Calificación de menciones"
  ) %>% 
  hc_add_series(
    data = dde,
    allowDrillToNode = TRUE,
    levelIsConstant = TRUE,
    textOverflow = "clip",
    dataLabels = list(color = "white"),
    levels = list(
      list(
        level = 1,
        borderWidth = 1,
        dataLabels = list(
          enabled = TRUE,
          verticalAlign = "top",
          align = "left",
          style = list(fontSize = "12px", textOutline = FALSE)
          )
        ),
      list(
        level = 2,
        borderWidth = 0,
        dataLabels = list(enabled = FALSE)
        )
      )
    ) %>% 
  # esto es para que el primer nivel, que no tiene color asigando, 
  # sea transparente.
  hc_colors("trasnparent")
```


```{r}
  base1 <- BD %>% 
    # filter(candidato %in% candida)%>%
    select(percepcion) %>% 
    unique() %>% 
    mutate(color=if_else(percepcion=="Buena",
                         "#FFFFFF",                     
                         if_else(percepcion=="Mala",
                                 "#FFFFFF","#FFFFFF")),
           id=str_to_id(percepcion)) %>% 
    rename("name"="percepcion")
  base2 <- BD %>% 
    # filter(candidato %in% candida)%>%
    count(percepcion, mencionGenerada) %>% 
    mutate(color=if_else(percepcion=="Buena" & 
                  mencionGenerada=="Boletines\n de prensa","#006d2c",
                  if_else(percepcion=="Buena" & 
                  mencionGenerada=="declaraciones",
                  "#31a354",
                  if_else(percepcion=="Buena" & 
                  mencionGenerada=="filtraciones",
                  "#74c476",
                  if_else(percepcion=="Mala" & 
                  mencionGenerada=="Boletines\n de prensa",
                  "#a50f15",
                  if_else(percepcion=="Mala" & 
                  mencionGenerada=="declaraciones",
                  "#de2d26",
                  if_else(percepcion=="Mala" & 
                  mencionGenerada=="filtraciones",
                  "#fb6a4a", 
                  if_else(percepcion=="Regular" & 
                  mencionGenerada=="Boletines\n de prensa",
                  "#636363",
                  if_else(percepcion=="Regular" & 
                  mencionGenerada=="declaraciones",
                  "#969696","#cccccc")))))))),
           parent=str_to_id(percepcion),
           id = as.character(row_number())) %>% 
    select(-percepcion) %>% 
    rename("name"= "mencionGenerada", "value"="n")
  dde <- list(base1, base2) %>%
    purrr::map(mutate_if, is.factor, as.character) %>% 
    bind_rows() %>% 
    list_parse() %>% 
    purrr::map(function(x) x[!is.na(x)])
  
highchart() %>% 
    hc_chart(type = "treemap") %>% 
    hc_title(
      text = paste0("Calificación de menciones ")
    ) %>%
    hc_add_series(
      data = dde,
      allowDrillToNode = TRUE,
      levelIsConstant = TRUE,
      textOverflow = "clip",
      dataLabels = list(color = "white"),
      levels = list(
        list(
          level = 1,
          borderWidth = 8,
          dataLabels = list(
            enabled = TRUE,
            verticalAlign = "top",
            align = "left",
            style = list(fontSize = "12px", textOutline = FALSE)
          )
        ),
        list(
          level = 2,
          borderWidth = 0,
          dataLabels = list(
            enabled = TRUE, 
             verticalAlign = "bottom",
            align = "left",
            style = list(fontSize = "12px", textOutline = FALSE)

                            )
        )
      )
    ) %>% 
    # esto es para que el primer nivel, que no tiene color asigando, 
    # sea transparente.
    hc_colors("trasnparent")%>% 
  
    hc_chart(style = list(fontFamily = "Avenir next"
    ))
  


```

```{r}
    n <- 1000
    v <- rep("Este es un texto a ser noticia", n)
    x <- c("12/01/2020", "13/01/2020","14/01/2020", "15/01/2020", "16/01/2020", "17/01/2020",
           "12/02/2020", "13/02/2020","14/02/2020", "15/02/2020", "16/02/2020", "17/02/2020",
           "12/01/2021", "13/01/2021","14/01/2021", "15/01/2021", "16/01/2021", "17/01/2021",
           "12/02/2021", "13/02/2021","14/02/2021", "15/02/2021", "16/02/2021", "17/02/2021")
    X <- sample(c("Buena", "Mala", "Regular"), n, replace=T) 
    filePath <- "http://www.sthda.com/sthda/RDoc/example-files/martin-luther-king-i-have-a-dream-speech.txt"
    text <- readLines(filePath) 
    remove <- c("", " ")
    text <- setdiff(text, remove)
    
    BD <- tibble(
    id = 1:n, title = v, calificacion = X,
    fecha = as.Date(rep(x, len = n)),
    text = rep(text, len = n),               
    temas = sample(c("Deportes", "Cultura", "Sociedad", "Tecnología", "Otros"), n, replace=T),
    entidad = sample(c("Michoacán", "Nuevo León"), 
                     n, replace = T, 
                     prob = c(.5, .5))
    ) %>% 
    mutate(temasOtro = case_when(temas == "Otros" ~ "Otro tema"), Noticias = 1)
    BD <- filter(BD, entidad==!!entidad())



temas_eleccion <- function(bd, pregunta, otro, x, titulo =""){
  bd_2 <- bd %>% filter({{ pregunta }} %in% c('Otro'))
  
  bd_1 = count(bd, {{ pregunta }}) %>%
    mutate(n  = round(100*n/sum(n),2)) %>%
    arrange(-n)
  
  nTot <- bd_1 %>%
    select(n) %>%
    mutate(sum = sum(n)) %>%
    select(sum)
  
  nTot <- nTot[1,1]$sum
  
  bd_1 <- bd_1 %>%
    filter(!{{ pregunta }} %in% c('Otro'))
  
  bd_1 <- bd_1 %>% mutate(n  = round(n/100, 2)) %>%
    spread(value = n, key = {{ pregunta }})
  
  bd_2 <- count(bd_2, {{ otro }}) %>%
    mutate(porcentaje  = round(100*n/sum(n), 2)) %>%
    filter(porcentaje > x)
  
  bd_2 <- select(bd_2, -porcentaje) 
  
  bd_2 <- bd_2 %>% mutate(n = round(n/nTot,2)) %>%
    spread(value = n, key = {{ otro }})
  
  if(nrow(bd_1) != nrow(bd_2)){
    
    Graph <- bd_1 %>%  gather(x, y) %>% mutate(y = round(y *100)) %>% 
      hchart(hcaes(x = x, y  =y), type = "line") %>%  
      hc_title(text =paste("<b>", titulo,"<b>") , align = "left", style = list(fontSize = "22px", color = "#13384D")) %>% 
      hc_plotOptions(line = list(lineWidth = 7, marker = list(radius = 7))) %>% 
      hc_yAxis(lineWidth =0, title = list(enabled = F),
               tickAmount = 4, showLastLabel = T,
               gridLineWidth  =1,
               gridLineDashStyle = "longdash",
               lineDashStyle = "longdash",
               labels = list(enabled = F,  format=paste0("{value}%"))) %>% 
      hc_xAxis(title = list(enabled = F), 
               lineWidth = 1,
               gridLineWidth =0,
               labels = list(style = list(
        fontFamily = "Avenir Next",
        # color = "#0c5776",
        fontSize = "16px"))) %>% 
      hc_colors("#4F5F80") %>% 
      hc_tooltip(headerFormat = "",
                 pointFormat= '<b>{point.y}%</b>',
                 borderWidth= 0, shape = "square", shadow=F) %>% 
            hc_chart(polar = T, style = list(fontFamily = "Avenir Next"))
  }else{
    
    df <- data.frame(bd_1, bd_2)
    titulos <- df %>%  colnames() %>%  str_to_sentence()
    df <- df %>%  set_names(titulos)
    Graph <-  df %>% gather(x, y) %>% mutate(y = round(y *100)) %>% 
      hchart(hcaes(x = x, y  =y), type = "line") %>%  
      hc_chart(polar = T, style = list(fontFamily = "Avenir Next")) %>% 
      hc_title(text = titulo,
           align = "left", style = list(fontSize = "22px", color = "#13384D")) %>% 
      hc_plotOptions(line = list(lineWidth = 5, marker = list(radius = 7))) %>% 
      hc_yAxis(lineWidth =0, title = list(enabled = F),
               # tickAmount = 3, 
               showLastLabel = T,
               gridLineDashStyle = "longdash",
               lineDashStyle = "longdash",
               labels = list(  format=paste0("{value}%"))) %>% 
      hc_xAxis(title = list(enabled = F), labels = list(style = list(color = "#0c5776", fontFamily  = "Avenir Next", fontSize = "18px"))) %>% 
      hc_colors("#81cbfe")%>% 
      hc_tooltip(headerFormat = "",
                 pointFormat= '<b>{point.y}%</b>',
                 borderWidth= 0, shape = "square", shadow=F)
    
  }
  
  return(Graph)
}



```

